# Generated by Django 3.2.3 on 2024-01-18 17:06

import django.core.validators
from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z', 'Поле username не соответствует формату.'), recipes.validators.validate_username_me], verbose_name='Имя пользователя'),
        ),
    ]
