# Generated by Django 3.2.3 on 2024-01-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipetag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_in_shopping_cart_recipe',
            new_name='shopping_cart_recipes',
        ),
    ]
