# Generated by Django 3.2.3 on 2024-01-24 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20240124_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(related_name='_recipes_user_subscriptions_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserSubscribe',
        ),
    ]
