# Generated by Django 3.2.3 on 2024-01-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20240131_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'default_related_name': 'recipe_ingredient', 'verbose_name': 'Ингредиент в рецептах', 'verbose_name_plural': 'Ингредиенты в рецептах'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'default_related_name': 'tag_ingredient', 'verbose_name': 'Тег в рецептах', 'verbose_name_plural': 'Теги в рецептах'},
        ),
    ]
