# Generated by Django 3.2.3 on 2024-02-05 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20240202_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'default_related_name': 'recipe_ingredient', 'ordering': ('recipe',), 'verbose_name': 'Ингредиент в рецептах', 'verbose_name_plural': 'Ингредиенты в рецептах'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'default_related_name': 'recipe_tag', 'ordering': ('recipe',), 'verbose_name': 'Тег в рецептах', 'verbose_name_plural': 'Теги в рецептах'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может быть меньше 1.'), django.core.validators.MaxValueValidator(32000, message='Время приготовления не может быть больше 32000.')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть меньше 1.'), django.core.validators.MaxValueValidator(32000, message='Количество не может быть больше 32000.')], verbose_name='Количество'),
        ),
    ]
